In [1]:
import numpy as np
import matplotlib.pyplot as plt

## membuat tensor

In [2]:
tensor=np.array([
                 [[23,50],[7,12]],
                 [[75,21],[57,12]],
                 [[57,67],[99,43]],
                 [[87,26],[18,84]]

                ]
                )

In [3]:
print(tensor)

[[[23 50]
  [ 7 12]]

 [[75 21]
  [57 12]]

 [[57 67]
  [99 43]]

 [[87 26]
  [18 84]]]


In [4]:
tensor.shape

(4, 2, 2)

#Perkalian matriks


In [5]:
A=np.array([[23,50,19],
            [7,12,109],
            [57,67,98]])
B=np.array([[17],[22],[19]])

In [6]:
B

array([[17],
       [22],
       [19]])

In [7]:
A.shape

(3, 3)

In [8]:
B.shape

(3, 1)

In [9]:
A*B

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

In [10]:
from numpy.linalg import inv

# menghitung determinan dan invers

In [11]:
print(inv(A))

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]


In [12]:
print(np.linalg.det(A))

131344.0000000002


# mentraspose matriks

In [13]:
#transpose mattrik A
transpose_A=A.T

In [14]:
transpose_A.shape

(3, 3)

In [15]:
A.shape

(3, 3)

In [16]:
print(A)
print(transpose_A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [29]:
A2=np.array([[1,-1],[6,4]])
A2

array([[ 1, -1],
       [ 6,  4]])

In [39]:
from numpy.linalg import eig

In [40]:
(eigen,vektor)=eig(A2)

In [41]:
print(eigen)
print(vektor)

[2.5+1.93649167j 2.5-1.93649167j]
[[-0.23145502+0.29880715j -0.23145502-0.29880715j]
 [ 0.9258201 +0.j          0.9258201 -0.j        ]]
